version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always

volumes:
  redis_data:
