version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_local
    ports:
      - "6379:6379"
    command: ["redis-server"]
    environment:
      REDIS_USERNAME: "redis_user"
    restart: always

volumes:
  redis_data:
