---
name: 🛠️ CI

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  static-code-analysis-workflow:
    name: "🔍 📄 Static Code Analysis"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: SetUp Python Project
        uses: sidkos/pytest_hooks/.github/actions/setup_python_project@main

      - name: Run Black
        if: always()
        uses: sidkos/pytest_hooks/.github/actions/black@main

      - name: Run Isort
        if: always()
        uses: sidkos/pytest_hooks/.github/actions/isort@main

      - name: Run Pycodestyle
        if: always()
        uses: sidkos/pytest_hooks/.github/actions/pycodestyle@main

      - name: Run Flake8
        if: always()
        uses: sidkos/pytest_hooks/.github/actions/flake8@main

      - name: Run MyPy
        if: always()
        uses: sidkos/pytest_hooks/.github/actions/mypy@main

      - name: Run Yaml Lint
        if: always()
        uses: sidkos/pytest_hooks/.github/actions/yamllint@main
